version: '3.4'

services:
  db:
    container_name: 'tabletop_of_many_things'
    image: 'postgres'
    platform: linux/amd64
    volumes:
      - './.postgres-data:/var/lib/postgresql/data'
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5438
    environment:
      # POSTGRES_USER: "bennett"
      POSTGRES_PASSWORD: "db"
